<a href="https://colab.research.google.com/github/gon-olmedo/data-science-cookbook/blob/main/numpy/1)_Creating_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy**: Creating Arrays

In [2]:
import numpy as np

In [3]:
# Create array of 2 rows and 3 columns filled with the number 0

np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
# create an array of 3 rows and 2 columns filled with random numbers

np.random.random((3,2))

array([[0.72153586, 0.43926964],
       [0.05956918, 0.53803081],
       [0.52013741, 0.41915312]])

In [5]:
# create an array a 1D array from numbers starting with 0
# ending with at 9 and with a difference of 3 per sequence
np.arange(0, 10, 3)

array([0, 3, 6, 9])

In [6]:
# You can even modify your arrays with simple aritmethic operations
a = np.arange(4)
a

array([0, 1, 2, 3])

In [7]:
a + 1

array([1, 2, 3, 4])

In [8]:
a * 3

array([0, 3, 6, 9])

In [9]:
# You can use aggregations on arrays

b = np.arange(1,9,2)
b

array([1, 3, 5, 7])

In [15]:
print(f'min: {b.min()}, max: {b.max()}, mean: {b.mean()}, median: {np.median(b)}')

min: 1, max: 7, mean: 4.0, median: 4.0
