<a href="https://colab.research.google.com/github/gon-olmedo/data-science-cookbook/blob/main/numpy/1)_Creating_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy**: Creating Arrays

In [9]:
import numpy as np

In [10]:
# Create array of 2 rows and 3 columns filled with the number 0

np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
# create an array of 3 rows and 2 columns filled with random numbers

np.random.random((3,2))

array([[0.07783958, 0.38903553],
       [0.5128756 , 0.24839494],
       [0.53668711, 0.94455951]])

In [14]:
# create an array a 1D array from numbers starting with 0
# ending with at 9 and with a difference of 3 per sequence
np.arange(0, 10, 3)

array([0, 3, 6, 9])